spring.application.name=dealership

# Database
spring.datasource.url=${DB_URL}/Dealership
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Security Key
api.security.token.secret=${JWT_SECRET_KEY}

spring.flyway.clean-on-validation-error=true
spring.flyway.validate-on-migrate=false

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs